#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thaw_Mix_Dashboard
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbANSRLTR_PROD")]
	public partial class AnsrConnectionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblDepartment(tblDepartment instance);
    partial void UpdatetblDepartment(tblDepartment instance);
    partial void DeletetblDepartment(tblDepartment instance);
    partial void InserttblEmployee(tblEmployee instance);
    partial void UpdatetblEmployee(tblEmployee instance);
    partial void DeletetblEmployee(tblEmployee instance);
    #endregion
		
		public AnsrConnectionDataContext() : 
				base(global::Thaw_Mix_Dashboard.Properties.Settings.Default.dbANSRLTR_PRODConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AnsrConnectionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnsrConnectionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnsrConnectionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnsrConnectionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblDepartment> tblDepartments
		{
			get
			{
				return this.GetTable<tblDepartment>();
			}
		}
		
		public System.Data.Linq.Table<tblEmployee> tblEmployees
		{
			get
			{
				return this.GetTable<tblEmployee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDepartment")]
	public partial class tblDepartment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _DEPT_ID;
		
		private string _NAME;
		
		private string _ABBREV_NAME;
		
		private int _DEPT_HEAD;
		
		private short _DIV_ID;
		
		private int _MEDICAL_DIRECTOR;
		
		private System.DateTime _INACTIVE_WHEN;
		
		private int _CHANGE_BY;
		
		private System.DateTime _CHANGE_WHEN;
		
		private bool _Dept_Head_Override_Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDEPT_IDChanging(short value);
    partial void OnDEPT_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnABBREV_NAMEChanging(string value);
    partial void OnABBREV_NAMEChanged();
    partial void OnDEPT_HEADChanging(int value);
    partial void OnDEPT_HEADChanged();
    partial void OnDIV_IDChanging(short value);
    partial void OnDIV_IDChanged();
    partial void OnMEDICAL_DIRECTORChanging(int value);
    partial void OnMEDICAL_DIRECTORChanged();
    partial void OnINACTIVE_WHENChanging(System.DateTime value);
    partial void OnINACTIVE_WHENChanged();
    partial void OnCHANGE_BYChanging(int value);
    partial void OnCHANGE_BYChanged();
    partial void OnCHANGE_WHENChanging(System.DateTime value);
    partial void OnCHANGE_WHENChanged();
    partial void OnDept_Head_Override_ActiveChanging(bool value);
    partial void OnDept_Head_Override_ActiveChanged();
    #endregion
		
		public tblDepartment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_ID", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short DEPT_ID
		{
			get
			{
				return this._DEPT_ID;
			}
			set
			{
				if ((this._DEPT_ID != value))
				{
					this.OnDEPT_IDChanging(value);
					this.SendPropertyChanging();
					this._DEPT_ID = value;
					this.SendPropertyChanged("DEPT_ID");
					this.OnDEPT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBREV_NAME", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string ABBREV_NAME
		{
			get
			{
				return this._ABBREV_NAME;
			}
			set
			{
				if ((this._ABBREV_NAME != value))
				{
					this.OnABBREV_NAMEChanging(value);
					this.SendPropertyChanging();
					this._ABBREV_NAME = value;
					this.SendPropertyChanged("ABBREV_NAME");
					this.OnABBREV_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_HEAD", DbType="Int NOT NULL")]
		public int DEPT_HEAD
		{
			get
			{
				return this._DEPT_HEAD;
			}
			set
			{
				if ((this._DEPT_HEAD != value))
				{
					this.OnDEPT_HEADChanging(value);
					this.SendPropertyChanging();
					this._DEPT_HEAD = value;
					this.SendPropertyChanged("DEPT_HEAD");
					this.OnDEPT_HEADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_ID", DbType="SmallInt NOT NULL")]
		public short DIV_ID
		{
			get
			{
				return this._DIV_ID;
			}
			set
			{
				if ((this._DIV_ID != value))
				{
					this.OnDIV_IDChanging(value);
					this.SendPropertyChanging();
					this._DIV_ID = value;
					this.SendPropertyChanged("DIV_ID");
					this.OnDIV_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEDICAL_DIRECTOR", DbType="Int NOT NULL")]
		public int MEDICAL_DIRECTOR
		{
			get
			{
				return this._MEDICAL_DIRECTOR;
			}
			set
			{
				if ((this._MEDICAL_DIRECTOR != value))
				{
					this.OnMEDICAL_DIRECTORChanging(value);
					this.SendPropertyChanging();
					this._MEDICAL_DIRECTOR = value;
					this.SendPropertyChanged("MEDICAL_DIRECTOR");
					this.OnMEDICAL_DIRECTORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INACTIVE_WHEN", DbType="SmallDateTime NOT NULL")]
		public System.DateTime INACTIVE_WHEN
		{
			get
			{
				return this._INACTIVE_WHEN;
			}
			set
			{
				if ((this._INACTIVE_WHEN != value))
				{
					this.OnINACTIVE_WHENChanging(value);
					this.SendPropertyChanging();
					this._INACTIVE_WHEN = value;
					this.SendPropertyChanged("INACTIVE_WHEN");
					this.OnINACTIVE_WHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGE_BY", DbType="Int NOT NULL")]
		public int CHANGE_BY
		{
			get
			{
				return this._CHANGE_BY;
			}
			set
			{
				if ((this._CHANGE_BY != value))
				{
					this.OnCHANGE_BYChanging(value);
					this.SendPropertyChanging();
					this._CHANGE_BY = value;
					this.SendPropertyChanged("CHANGE_BY");
					this.OnCHANGE_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGE_WHEN", DbType="SmallDateTime NOT NULL")]
		public System.DateTime CHANGE_WHEN
		{
			get
			{
				return this._CHANGE_WHEN;
			}
			set
			{
				if ((this._CHANGE_WHEN != value))
				{
					this.OnCHANGE_WHENChanging(value);
					this.SendPropertyChanging();
					this._CHANGE_WHEN = value;
					this.SendPropertyChanged("CHANGE_WHEN");
					this.OnCHANGE_WHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept_Head_Override_Active", DbType="Bit NOT NULL")]
		public bool Dept_Head_Override_Active
		{
			get
			{
				return this._Dept_Head_Override_Active;
			}
			set
			{
				if ((this._Dept_Head_Override_Active != value))
				{
					this.OnDept_Head_Override_ActiveChanging(value);
					this.SendPropertyChanging();
					this._Dept_Head_Override_Active = value;
					this.SendPropertyChanged("Dept_Head_Override_Active");
					this.OnDept_Head_Override_ActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEmployee")]
	public partial class tblEmployee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EMPLOYEE_ID;
		
		private short _JOB_ID;
		
		private string _FIRST_NAME;
		
		private char _MID_INITIAL;
		
		private string _LAST_NAME;
		
		private string _SALES_REP_CODE;
		
		private string _SHORT_CREDENTIAL;
		
		private string _ADRS_LINE1;
		
		private string _ADRS_LINE2;
		
		private string _CITY;
		
		private string _STATE;
		
		private string _ZIP_CODE;
		
		private string _COUNTRY;
		
		private string _HOME_PHONE_NUM;
		
		private string _WORK_PHONE_NUM;
		
		private string _WORK_PHONE_EXT;
		
		private string _WORK_PHONE_FAX;
		
		private string _PAGER_PHONE_NUM;
		
		private short _DEPT_ID;
		
		private string _WORK_LOC_ID;
		
		private string _LAN_ID;
		
		private string _COMPUTER_NAME;
		
		private short _COMPUTER_ID;
		
		private string _MAIL_NAME;
		
		private int _ROUTE_REMINDER_TO_WHO;
		
		private char _PRI_DEPT_CONTACT;
		
		private char _STATUS;
		
		private char _SEND_EMAIL_VIA;
		
		private System.DateTime _HIRE_WHEN;
		
		private System.DateTime _PENDING_TERM_WHEN;
		
		private System.DateTime _TERMINATE_WHEN;
		
		private char _TERMINATE_WHY;
		
		private char _RECORD_TYPE;
		
		private decimal _COMMENT;
		
		private int _CHANGE_BY;
		
		private System.DateTime _CHANGE_WHEN;
		
		private int _Supervisor;
		
		private int _Manager;
		
		private short _Hours;
		
		private System.DateTime _DEPT_HIRE_WHEN;
		
		private System.DateTime _POSITION_HIRE_WHEN;
		
		private int _SPONSOR_ID;
		
		private string _PREFERRED_NAME;
		
		private string _LOCKER_NUMBER;
		
		private string _LOCKER_COMBINATION;
		
		private int _WORK_TEAM_NUMBER;
		
		private string _ER_CONTACT_NAME;
		
		private string _ER_CONTACT_PHONE;
		
		private byte _YEARS_LAB_EXPERIENCE;
		
		private byte _ARUP_LAB_EXPERIENCE;
		
		private string _LIS_SIGNON;
		
		private System.DateTime _PERF_REVIEW_WHEN;
		
		private char _PERF_REVIEW_TYPE;
		
		private char _TESTING_ELIGIBILITY;
		
		private int _DIVISIONMANAGERID;
		
		private string _Email_Address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEMPLOYEE_IDChanging(int value);
    partial void OnEMPLOYEE_IDChanged();
    partial void OnJOB_IDChanging(short value);
    partial void OnJOB_IDChanged();
    partial void OnFIRST_NAMEChanging(string value);
    partial void OnFIRST_NAMEChanged();
    partial void OnMID_INITIALChanging(char value);
    partial void OnMID_INITIALChanged();
    partial void OnLAST_NAMEChanging(string value);
    partial void OnLAST_NAMEChanged();
    partial void OnSALES_REP_CODEChanging(string value);
    partial void OnSALES_REP_CODEChanged();
    partial void OnSHORT_CREDENTIALChanging(string value);
    partial void OnSHORT_CREDENTIALChanged();
    partial void OnADRS_LINE1Changing(string value);
    partial void OnADRS_LINE1Changed();
    partial void OnADRS_LINE2Changing(string value);
    partial void OnADRS_LINE2Changed();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnSTATEChanging(string value);
    partial void OnSTATEChanged();
    partial void OnZIP_CODEChanging(string value);
    partial void OnZIP_CODEChanged();
    partial void OnCOUNTRYChanging(string value);
    partial void OnCOUNTRYChanged();
    partial void OnHOME_PHONE_NUMChanging(string value);
    partial void OnHOME_PHONE_NUMChanged();
    partial void OnWORK_PHONE_NUMChanging(string value);
    partial void OnWORK_PHONE_NUMChanged();
    partial void OnWORK_PHONE_EXTChanging(string value);
    partial void OnWORK_PHONE_EXTChanged();
    partial void OnWORK_PHONE_FAXChanging(string value);
    partial void OnWORK_PHONE_FAXChanged();
    partial void OnPAGER_PHONE_NUMChanging(string value);
    partial void OnPAGER_PHONE_NUMChanged();
    partial void OnDEPT_IDChanging(short value);
    partial void OnDEPT_IDChanged();
    partial void OnWORK_LOC_IDChanging(string value);
    partial void OnWORK_LOC_IDChanged();
    partial void OnLAN_IDChanging(string value);
    partial void OnLAN_IDChanged();
    partial void OnCOMPUTER_NAMEChanging(string value);
    partial void OnCOMPUTER_NAMEChanged();
    partial void OnCOMPUTER_IDChanging(short value);
    partial void OnCOMPUTER_IDChanged();
    partial void OnMAIL_NAMEChanging(string value);
    partial void OnMAIL_NAMEChanged();
    partial void OnROUTE_REMINDER_TO_WHOChanging(int value);
    partial void OnROUTE_REMINDER_TO_WHOChanged();
    partial void OnPRI_DEPT_CONTACTChanging(char value);
    partial void OnPRI_DEPT_CONTACTChanged();
    partial void OnSTATUSChanging(char value);
    partial void OnSTATUSChanged();
    partial void OnSEND_EMAIL_VIAChanging(char value);
    partial void OnSEND_EMAIL_VIAChanged();
    partial void OnHIRE_WHENChanging(System.DateTime value);
    partial void OnHIRE_WHENChanged();
    partial void OnPENDING_TERM_WHENChanging(System.DateTime value);
    partial void OnPENDING_TERM_WHENChanged();
    partial void OnTERMINATE_WHENChanging(System.DateTime value);
    partial void OnTERMINATE_WHENChanged();
    partial void OnTERMINATE_WHYChanging(char value);
    partial void OnTERMINATE_WHYChanged();
    partial void OnRECORD_TYPEChanging(char value);
    partial void OnRECORD_TYPEChanged();
    partial void OnCOMMENTChanging(decimal value);
    partial void OnCOMMENTChanged();
    partial void OnCHANGE_BYChanging(int value);
    partial void OnCHANGE_BYChanged();
    partial void OnCHANGE_WHENChanging(System.DateTime value);
    partial void OnCHANGE_WHENChanged();
    partial void OnSupervisorChanging(int value);
    partial void OnSupervisorChanged();
    partial void OnManagerChanging(int value);
    partial void OnManagerChanged();
    partial void OnHoursChanging(short value);
    partial void OnHoursChanged();
    partial void OnDEPT_HIRE_WHENChanging(System.DateTime value);
    partial void OnDEPT_HIRE_WHENChanged();
    partial void OnPOSITION_HIRE_WHENChanging(System.DateTime value);
    partial void OnPOSITION_HIRE_WHENChanged();
    partial void OnSPONSOR_IDChanging(int value);
    partial void OnSPONSOR_IDChanged();
    partial void OnPREFERRED_NAMEChanging(string value);
    partial void OnPREFERRED_NAMEChanged();
    partial void OnLOCKER_NUMBERChanging(string value);
    partial void OnLOCKER_NUMBERChanged();
    partial void OnLOCKER_COMBINATIONChanging(string value);
    partial void OnLOCKER_COMBINATIONChanged();
    partial void OnWORK_TEAM_NUMBERChanging(int value);
    partial void OnWORK_TEAM_NUMBERChanged();
    partial void OnER_CONTACT_NAMEChanging(string value);
    partial void OnER_CONTACT_NAMEChanged();
    partial void OnER_CONTACT_PHONEChanging(string value);
    partial void OnER_CONTACT_PHONEChanged();
    partial void OnYEARS_LAB_EXPERIENCEChanging(byte value);
    partial void OnYEARS_LAB_EXPERIENCEChanged();
    partial void OnARUP_LAB_EXPERIENCEChanging(byte value);
    partial void OnARUP_LAB_EXPERIENCEChanged();
    partial void OnLIS_SIGNONChanging(string value);
    partial void OnLIS_SIGNONChanged();
    partial void OnPERF_REVIEW_WHENChanging(System.DateTime value);
    partial void OnPERF_REVIEW_WHENChanged();
    partial void OnPERF_REVIEW_TYPEChanging(char value);
    partial void OnPERF_REVIEW_TYPEChanged();
    partial void OnTESTING_ELIGIBILITYChanging(char value);
    partial void OnTESTING_ELIGIBILITYChanged();
    partial void OnDIVISIONMANAGERIDChanging(int value);
    partial void OnDIVISIONMANAGERIDChanged();
    partial void OnEmail_AddressChanging(string value);
    partial void OnEmail_AddressChanged();
    #endregion
		
		public tblEmployee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this.OnEMPLOYEE_IDChanging(value);
					this.SendPropertyChanging();
					this._EMPLOYEE_ID = value;
					this.SendPropertyChanged("EMPLOYEE_ID");
					this.OnEMPLOYEE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_ID", DbType="SmallInt NOT NULL")]
		public short JOB_ID
		{
			get
			{
				return this._JOB_ID;
			}
			set
			{
				if ((this._JOB_ID != value))
				{
					this.OnJOB_IDChanging(value);
					this.SendPropertyChanging();
					this._JOB_ID = value;
					this.SendPropertyChanged("JOB_ID");
					this.OnJOB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_NAME", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string FIRST_NAME
		{
			get
			{
				return this._FIRST_NAME;
			}
			set
			{
				if ((this._FIRST_NAME != value))
				{
					this.OnFIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FIRST_NAME = value;
					this.SendPropertyChanged("FIRST_NAME");
					this.OnFIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MID_INITIAL", DbType="Char(1) NOT NULL")]
		public char MID_INITIAL
		{
			get
			{
				return this._MID_INITIAL;
			}
			set
			{
				if ((this._MID_INITIAL != value))
				{
					this.OnMID_INITIALChanging(value);
					this.SendPropertyChanging();
					this._MID_INITIAL = value;
					this.SendPropertyChanged("MID_INITIAL");
					this.OnMID_INITIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_NAME", DbType="VarChar(20)")]
		public string LAST_NAME
		{
			get
			{
				return this._LAST_NAME;
			}
			set
			{
				if ((this._LAST_NAME != value))
				{
					this.OnLAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_NAME = value;
					this.SendPropertyChanged("LAST_NAME");
					this.OnLAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALES_REP_CODE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SALES_REP_CODE
		{
			get
			{
				return this._SALES_REP_CODE;
			}
			set
			{
				if ((this._SALES_REP_CODE != value))
				{
					this.OnSALES_REP_CODEChanging(value);
					this.SendPropertyChanging();
					this._SALES_REP_CODE = value;
					this.SendPropertyChanged("SALES_REP_CODE");
					this.OnSALES_REP_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHORT_CREDENTIAL", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SHORT_CREDENTIAL
		{
			get
			{
				return this._SHORT_CREDENTIAL;
			}
			set
			{
				if ((this._SHORT_CREDENTIAL != value))
				{
					this.OnSHORT_CREDENTIALChanging(value);
					this.SendPropertyChanging();
					this._SHORT_CREDENTIAL = value;
					this.SendPropertyChanged("SHORT_CREDENTIAL");
					this.OnSHORT_CREDENTIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRS_LINE1", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string ADRS_LINE1
		{
			get
			{
				return this._ADRS_LINE1;
			}
			set
			{
				if ((this._ADRS_LINE1 != value))
				{
					this.OnADRS_LINE1Changing(value);
					this.SendPropertyChanging();
					this._ADRS_LINE1 = value;
					this.SendPropertyChanged("ADRS_LINE1");
					this.OnADRS_LINE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRS_LINE2", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string ADRS_LINE2
		{
			get
			{
				return this._ADRS_LINE2;
			}
			set
			{
				if ((this._ADRS_LINE2 != value))
				{
					this.OnADRS_LINE2Changing(value);
					this.SendPropertyChanging();
					this._ADRS_LINE2 = value;
					this.SendPropertyChanged("ADRS_LINE2");
					this.OnADRS_LINE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="VarChar(28) NOT NULL", CanBeNull=false)]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this.OnSTATEChanging(value);
					this.SendPropertyChanging();
					this._STATE = value;
					this.SendPropertyChanged("STATE");
					this.OnSTATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP_CODE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ZIP_CODE
		{
			get
			{
				return this._ZIP_CODE;
			}
			set
			{
				if ((this._ZIP_CODE != value))
				{
					this.OnZIP_CODEChanging(value);
					this.SendPropertyChanging();
					this._ZIP_CODE = value;
					this.SendPropertyChanged("ZIP_CODE");
					this.OnZIP_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string COUNTRY
		{
			get
			{
				return this._COUNTRY;
			}
			set
			{
				if ((this._COUNTRY != value))
				{
					this.OnCOUNTRYChanging(value);
					this.SendPropertyChanging();
					this._COUNTRY = value;
					this.SendPropertyChanged("COUNTRY");
					this.OnCOUNTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOME_PHONE_NUM", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string HOME_PHONE_NUM
		{
			get
			{
				return this._HOME_PHONE_NUM;
			}
			set
			{
				if ((this._HOME_PHONE_NUM != value))
				{
					this.OnHOME_PHONE_NUMChanging(value);
					this.SendPropertyChanging();
					this._HOME_PHONE_NUM = value;
					this.SendPropertyChanged("HOME_PHONE_NUM");
					this.OnHOME_PHONE_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_PHONE_NUM", DbType="VarChar(12)")]
		public string WORK_PHONE_NUM
		{
			get
			{
				return this._WORK_PHONE_NUM;
			}
			set
			{
				if ((this._WORK_PHONE_NUM != value))
				{
					this.OnWORK_PHONE_NUMChanging(value);
					this.SendPropertyChanging();
					this._WORK_PHONE_NUM = value;
					this.SendPropertyChanged("WORK_PHONE_NUM");
					this.OnWORK_PHONE_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_PHONE_EXT", DbType="Char(6)")]
		public string WORK_PHONE_EXT
		{
			get
			{
				return this._WORK_PHONE_EXT;
			}
			set
			{
				if ((this._WORK_PHONE_EXT != value))
				{
					this.OnWORK_PHONE_EXTChanging(value);
					this.SendPropertyChanging();
					this._WORK_PHONE_EXT = value;
					this.SendPropertyChanged("WORK_PHONE_EXT");
					this.OnWORK_PHONE_EXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_PHONE_FAX", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string WORK_PHONE_FAX
		{
			get
			{
				return this._WORK_PHONE_FAX;
			}
			set
			{
				if ((this._WORK_PHONE_FAX != value))
				{
					this.OnWORK_PHONE_FAXChanging(value);
					this.SendPropertyChanging();
					this._WORK_PHONE_FAX = value;
					this.SendPropertyChanged("WORK_PHONE_FAX");
					this.OnWORK_PHONE_FAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAGER_PHONE_NUM", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PAGER_PHONE_NUM
		{
			get
			{
				return this._PAGER_PHONE_NUM;
			}
			set
			{
				if ((this._PAGER_PHONE_NUM != value))
				{
					this.OnPAGER_PHONE_NUMChanging(value);
					this.SendPropertyChanging();
					this._PAGER_PHONE_NUM = value;
					this.SendPropertyChanged("PAGER_PHONE_NUM");
					this.OnPAGER_PHONE_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_ID", DbType="SmallInt NOT NULL")]
		public short DEPT_ID
		{
			get
			{
				return this._DEPT_ID;
			}
			set
			{
				if ((this._DEPT_ID != value))
				{
					this.OnDEPT_IDChanging(value);
					this.SendPropertyChanging();
					this._DEPT_ID = value;
					this.SendPropertyChanged("DEPT_ID");
					this.OnDEPT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_LOC_ID", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string WORK_LOC_ID
		{
			get
			{
				return this._WORK_LOC_ID;
			}
			set
			{
				if ((this._WORK_LOC_ID != value))
				{
					this.OnWORK_LOC_IDChanging(value);
					this.SendPropertyChanging();
					this._WORK_LOC_ID = value;
					this.SendPropertyChanged("WORK_LOC_ID");
					this.OnWORK_LOC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAN_ID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string LAN_ID
		{
			get
			{
				return this._LAN_ID;
			}
			set
			{
				if ((this._LAN_ID != value))
				{
					this.OnLAN_IDChanging(value);
					this.SendPropertyChanging();
					this._LAN_ID = value;
					this.SendPropertyChanged("LAN_ID");
					this.OnLAN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPUTER_NAME", DbType="VarChar(36) NOT NULL", CanBeNull=false)]
		public string COMPUTER_NAME
		{
			get
			{
				return this._COMPUTER_NAME;
			}
			set
			{
				if ((this._COMPUTER_NAME != value))
				{
					this.OnCOMPUTER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._COMPUTER_NAME = value;
					this.SendPropertyChanged("COMPUTER_NAME");
					this.OnCOMPUTER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPUTER_ID", DbType="SmallInt NOT NULL")]
		public short COMPUTER_ID
		{
			get
			{
				return this._COMPUTER_ID;
			}
			set
			{
				if ((this._COMPUTER_ID != value))
				{
					this.OnCOMPUTER_IDChanging(value);
					this.SendPropertyChanging();
					this._COMPUTER_ID = value;
					this.SendPropertyChanged("COMPUTER_ID");
					this.OnCOMPUTER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIL_NAME", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string MAIL_NAME
		{
			get
			{
				return this._MAIL_NAME;
			}
			set
			{
				if ((this._MAIL_NAME != value))
				{
					this.OnMAIL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._MAIL_NAME = value;
					this.SendPropertyChanged("MAIL_NAME");
					this.OnMAIL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROUTE_REMINDER_TO_WHO", DbType="Int NOT NULL")]
		public int ROUTE_REMINDER_TO_WHO
		{
			get
			{
				return this._ROUTE_REMINDER_TO_WHO;
			}
			set
			{
				if ((this._ROUTE_REMINDER_TO_WHO != value))
				{
					this.OnROUTE_REMINDER_TO_WHOChanging(value);
					this.SendPropertyChanging();
					this._ROUTE_REMINDER_TO_WHO = value;
					this.SendPropertyChanged("ROUTE_REMINDER_TO_WHO");
					this.OnROUTE_REMINDER_TO_WHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRI_DEPT_CONTACT", DbType="Char(1) NOT NULL")]
		public char PRI_DEPT_CONTACT
		{
			get
			{
				return this._PRI_DEPT_CONTACT;
			}
			set
			{
				if ((this._PRI_DEPT_CONTACT != value))
				{
					this.OnPRI_DEPT_CONTACTChanging(value);
					this.SendPropertyChanging();
					this._PRI_DEPT_CONTACT = value;
					this.SendPropertyChanged("PRI_DEPT_CONTACT");
					this.OnPRI_DEPT_CONTACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Char(1) NOT NULL")]
		public char STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEND_EMAIL_VIA", DbType="Char(1) NOT NULL")]
		public char SEND_EMAIL_VIA
		{
			get
			{
				return this._SEND_EMAIL_VIA;
			}
			set
			{
				if ((this._SEND_EMAIL_VIA != value))
				{
					this.OnSEND_EMAIL_VIAChanging(value);
					this.SendPropertyChanging();
					this._SEND_EMAIL_VIA = value;
					this.SendPropertyChanged("SEND_EMAIL_VIA");
					this.OnSEND_EMAIL_VIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_WHEN", DbType="SmallDateTime NOT NULL")]
		public System.DateTime HIRE_WHEN
		{
			get
			{
				return this._HIRE_WHEN;
			}
			set
			{
				if ((this._HIRE_WHEN != value))
				{
					this.OnHIRE_WHENChanging(value);
					this.SendPropertyChanging();
					this._HIRE_WHEN = value;
					this.SendPropertyChanged("HIRE_WHEN");
					this.OnHIRE_WHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PENDING_TERM_WHEN", DbType="SmallDateTime NOT NULL")]
		public System.DateTime PENDING_TERM_WHEN
		{
			get
			{
				return this._PENDING_TERM_WHEN;
			}
			set
			{
				if ((this._PENDING_TERM_WHEN != value))
				{
					this.OnPENDING_TERM_WHENChanging(value);
					this.SendPropertyChanging();
					this._PENDING_TERM_WHEN = value;
					this.SendPropertyChanged("PENDING_TERM_WHEN");
					this.OnPENDING_TERM_WHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINATE_WHEN", DbType="SmallDateTime NOT NULL")]
		public System.DateTime TERMINATE_WHEN
		{
			get
			{
				return this._TERMINATE_WHEN;
			}
			set
			{
				if ((this._TERMINATE_WHEN != value))
				{
					this.OnTERMINATE_WHENChanging(value);
					this.SendPropertyChanging();
					this._TERMINATE_WHEN = value;
					this.SendPropertyChanged("TERMINATE_WHEN");
					this.OnTERMINATE_WHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINATE_WHY", DbType="Char(1) NOT NULL")]
		public char TERMINATE_WHY
		{
			get
			{
				return this._TERMINATE_WHY;
			}
			set
			{
				if ((this._TERMINATE_WHY != value))
				{
					this.OnTERMINATE_WHYChanging(value);
					this.SendPropertyChanging();
					this._TERMINATE_WHY = value;
					this.SendPropertyChanged("TERMINATE_WHY");
					this.OnTERMINATE_WHYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORD_TYPE", DbType="Char(1) NOT NULL")]
		public char RECORD_TYPE
		{
			get
			{
				return this._RECORD_TYPE;
			}
			set
			{
				if ((this._RECORD_TYPE != value))
				{
					this.OnRECORD_TYPEChanging(value);
					this.SendPropertyChanging();
					this._RECORD_TYPE = value;
					this.SendPropertyChanged("RECORD_TYPE");
					this.OnRECORD_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENT", DbType="Decimal(15,0) NOT NULL")]
		public decimal COMMENT
		{
			get
			{
				return this._COMMENT;
			}
			set
			{
				if ((this._COMMENT != value))
				{
					this.OnCOMMENTChanging(value);
					this.SendPropertyChanging();
					this._COMMENT = value;
					this.SendPropertyChanged("COMMENT");
					this.OnCOMMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGE_BY", DbType="Int NOT NULL")]
		public int CHANGE_BY
		{
			get
			{
				return this._CHANGE_BY;
			}
			set
			{
				if ((this._CHANGE_BY != value))
				{
					this.OnCHANGE_BYChanging(value);
					this.SendPropertyChanging();
					this._CHANGE_BY = value;
					this.SendPropertyChanged("CHANGE_BY");
					this.OnCHANGE_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGE_WHEN", DbType="SmallDateTime NOT NULL")]
		public System.DateTime CHANGE_WHEN
		{
			get
			{
				return this._CHANGE_WHEN;
			}
			set
			{
				if ((this._CHANGE_WHEN != value))
				{
					this.OnCHANGE_WHENChanging(value);
					this.SendPropertyChanging();
					this._CHANGE_WHEN = value;
					this.SendPropertyChanged("CHANGE_WHEN");
					this.OnCHANGE_WHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supervisor", DbType="Int NOT NULL")]
		public int Supervisor
		{
			get
			{
				return this._Supervisor;
			}
			set
			{
				if ((this._Supervisor != value))
				{
					this.OnSupervisorChanging(value);
					this.SendPropertyChanging();
					this._Supervisor = value;
					this.SendPropertyChanged("Supervisor");
					this.OnSupervisorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manager", DbType="Int NOT NULL")]
		public int Manager
		{
			get
			{
				return this._Manager;
			}
			set
			{
				if ((this._Manager != value))
				{
					this.OnManagerChanging(value);
					this.SendPropertyChanging();
					this._Manager = value;
					this.SendPropertyChanged("Manager");
					this.OnManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hours", DbType="SmallInt NOT NULL")]
		public short Hours
		{
			get
			{
				return this._Hours;
			}
			set
			{
				if ((this._Hours != value))
				{
					this.OnHoursChanging(value);
					this.SendPropertyChanging();
					this._Hours = value;
					this.SendPropertyChanged("Hours");
					this.OnHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_HIRE_WHEN", DbType="SmallDateTime NOT NULL")]
		public System.DateTime DEPT_HIRE_WHEN
		{
			get
			{
				return this._DEPT_HIRE_WHEN;
			}
			set
			{
				if ((this._DEPT_HIRE_WHEN != value))
				{
					this.OnDEPT_HIRE_WHENChanging(value);
					this.SendPropertyChanging();
					this._DEPT_HIRE_WHEN = value;
					this.SendPropertyChanged("DEPT_HIRE_WHEN");
					this.OnDEPT_HIRE_WHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_HIRE_WHEN", DbType="SmallDateTime NOT NULL")]
		public System.DateTime POSITION_HIRE_WHEN
		{
			get
			{
				return this._POSITION_HIRE_WHEN;
			}
			set
			{
				if ((this._POSITION_HIRE_WHEN != value))
				{
					this.OnPOSITION_HIRE_WHENChanging(value);
					this.SendPropertyChanging();
					this._POSITION_HIRE_WHEN = value;
					this.SendPropertyChanged("POSITION_HIRE_WHEN");
					this.OnPOSITION_HIRE_WHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPONSOR_ID", DbType="Int NOT NULL")]
		public int SPONSOR_ID
		{
			get
			{
				return this._SPONSOR_ID;
			}
			set
			{
				if ((this._SPONSOR_ID != value))
				{
					this.OnSPONSOR_IDChanging(value);
					this.SendPropertyChanging();
					this._SPONSOR_ID = value;
					this.SendPropertyChanged("SPONSOR_ID");
					this.OnSPONSOR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREFERRED_NAME", DbType="VarChar(20)")]
		public string PREFERRED_NAME
		{
			get
			{
				return this._PREFERRED_NAME;
			}
			set
			{
				if ((this._PREFERRED_NAME != value))
				{
					this.OnPREFERRED_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PREFERRED_NAME = value;
					this.SendPropertyChanged("PREFERRED_NAME");
					this.OnPREFERRED_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCKER_NUMBER", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string LOCKER_NUMBER
		{
			get
			{
				return this._LOCKER_NUMBER;
			}
			set
			{
				if ((this._LOCKER_NUMBER != value))
				{
					this.OnLOCKER_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._LOCKER_NUMBER = value;
					this.SendPropertyChanged("LOCKER_NUMBER");
					this.OnLOCKER_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCKER_COMBINATION", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string LOCKER_COMBINATION
		{
			get
			{
				return this._LOCKER_COMBINATION;
			}
			set
			{
				if ((this._LOCKER_COMBINATION != value))
				{
					this.OnLOCKER_COMBINATIONChanging(value);
					this.SendPropertyChanging();
					this._LOCKER_COMBINATION = value;
					this.SendPropertyChanged("LOCKER_COMBINATION");
					this.OnLOCKER_COMBINATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_TEAM_NUMBER", DbType="Int NOT NULL")]
		public int WORK_TEAM_NUMBER
		{
			get
			{
				return this._WORK_TEAM_NUMBER;
			}
			set
			{
				if ((this._WORK_TEAM_NUMBER != value))
				{
					this.OnWORK_TEAM_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._WORK_TEAM_NUMBER = value;
					this.SendPropertyChanged("WORK_TEAM_NUMBER");
					this.OnWORK_TEAM_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ER_CONTACT_NAME", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ER_CONTACT_NAME
		{
			get
			{
				return this._ER_CONTACT_NAME;
			}
			set
			{
				if ((this._ER_CONTACT_NAME != value))
				{
					this.OnER_CONTACT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._ER_CONTACT_NAME = value;
					this.SendPropertyChanged("ER_CONTACT_NAME");
					this.OnER_CONTACT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ER_CONTACT_PHONE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ER_CONTACT_PHONE
		{
			get
			{
				return this._ER_CONTACT_PHONE;
			}
			set
			{
				if ((this._ER_CONTACT_PHONE != value))
				{
					this.OnER_CONTACT_PHONEChanging(value);
					this.SendPropertyChanging();
					this._ER_CONTACT_PHONE = value;
					this.SendPropertyChanged("ER_CONTACT_PHONE");
					this.OnER_CONTACT_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEARS_LAB_EXPERIENCE", DbType="TinyInt NOT NULL")]
		public byte YEARS_LAB_EXPERIENCE
		{
			get
			{
				return this._YEARS_LAB_EXPERIENCE;
			}
			set
			{
				if ((this._YEARS_LAB_EXPERIENCE != value))
				{
					this.OnYEARS_LAB_EXPERIENCEChanging(value);
					this.SendPropertyChanging();
					this._YEARS_LAB_EXPERIENCE = value;
					this.SendPropertyChanged("YEARS_LAB_EXPERIENCE");
					this.OnYEARS_LAB_EXPERIENCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARUP_LAB_EXPERIENCE", DbType="TinyInt NOT NULL")]
		public byte ARUP_LAB_EXPERIENCE
		{
			get
			{
				return this._ARUP_LAB_EXPERIENCE;
			}
			set
			{
				if ((this._ARUP_LAB_EXPERIENCE != value))
				{
					this.OnARUP_LAB_EXPERIENCEChanging(value);
					this.SendPropertyChanging();
					this._ARUP_LAB_EXPERIENCE = value;
					this.SendPropertyChanged("ARUP_LAB_EXPERIENCE");
					this.OnARUP_LAB_EXPERIENCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIS_SIGNON", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string LIS_SIGNON
		{
			get
			{
				return this._LIS_SIGNON;
			}
			set
			{
				if ((this._LIS_SIGNON != value))
				{
					this.OnLIS_SIGNONChanging(value);
					this.SendPropertyChanging();
					this._LIS_SIGNON = value;
					this.SendPropertyChanged("LIS_SIGNON");
					this.OnLIS_SIGNONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERF_REVIEW_WHEN", DbType="SmallDateTime NOT NULL")]
		public System.DateTime PERF_REVIEW_WHEN
		{
			get
			{
				return this._PERF_REVIEW_WHEN;
			}
			set
			{
				if ((this._PERF_REVIEW_WHEN != value))
				{
					this.OnPERF_REVIEW_WHENChanging(value);
					this.SendPropertyChanging();
					this._PERF_REVIEW_WHEN = value;
					this.SendPropertyChanged("PERF_REVIEW_WHEN");
					this.OnPERF_REVIEW_WHENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERF_REVIEW_TYPE", DbType="Char(1) NOT NULL")]
		public char PERF_REVIEW_TYPE
		{
			get
			{
				return this._PERF_REVIEW_TYPE;
			}
			set
			{
				if ((this._PERF_REVIEW_TYPE != value))
				{
					this.OnPERF_REVIEW_TYPEChanging(value);
					this.SendPropertyChanging();
					this._PERF_REVIEW_TYPE = value;
					this.SendPropertyChanged("PERF_REVIEW_TYPE");
					this.OnPERF_REVIEW_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TESTING_ELIGIBILITY", DbType="Char(1) NOT NULL")]
		public char TESTING_ELIGIBILITY
		{
			get
			{
				return this._TESTING_ELIGIBILITY;
			}
			set
			{
				if ((this._TESTING_ELIGIBILITY != value))
				{
					this.OnTESTING_ELIGIBILITYChanging(value);
					this.SendPropertyChanging();
					this._TESTING_ELIGIBILITY = value;
					this.SendPropertyChanged("TESTING_ELIGIBILITY");
					this.OnTESTING_ELIGIBILITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVISIONMANAGERID", DbType="Int NOT NULL")]
		public int DIVISIONMANAGERID
		{
			get
			{
				return this._DIVISIONMANAGERID;
			}
			set
			{
				if ((this._DIVISIONMANAGERID != value))
				{
					this.OnDIVISIONMANAGERIDChanging(value);
					this.SendPropertyChanging();
					this._DIVISIONMANAGERID = value;
					this.SendPropertyChanged("DIVISIONMANAGERID");
					this.OnDIVISIONMANAGERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_Address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email_Address
		{
			get
			{
				return this._Email_Address;
			}
			set
			{
				if ((this._Email_Address != value))
				{
					this.OnEmail_AddressChanging(value);
					this.SendPropertyChanging();
					this._Email_Address = value;
					this.SendPropertyChanged("Email_Address");
					this.OnEmail_AddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
