//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thaw_Mix_Dashboard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int LogOutTime {
            get {
                return ((int)(this["LogOutTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANSRLTR;Initial Catalog=dbANSRLTR_PROD;User ID=SuppSrvcsIT")]
        public string dbANSRLTR_PRODConnectionString {
            get {
                return ((string)(this["dbANSRLTR_PRODConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESP-ODS;Initial Catalog=ContainerManagement-ODS;User ID=SuppSrvcsIT")]
        public string ContainerManagement_ODSConnectionString {
            get {
                return ((string)(this["ContainerManagement_ODSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQLLIB01;Initial Catalog=SpecimenTracker;Persist Security Info=True;U" +
            "ser ID=SpecimenTracker;")]
        public string SpecimenTracker_ConnectionString {
            get {
                return ((string)(this["SpecimenTracker_ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int ApplicationID {
            get {
                return ((int)(this["ApplicationID"]));
            }
            set {
                this["ApplicationID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("218,232,240,245,236,255,243")]
        public string DeptAccess {
            get {
                return ((string)(this["DeptAccess"]));
            }
            set {
                this["DeptAccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CheckedInTimeMinutes {
            get {
                return ((int)(this["CheckedInTimeMinutes"]));
            }
            set {
                this["CheckedInTimeMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int CheckedInTimeHours {
            get {
                return ((int)(this["CheckedInTimeHours"]));
            }
            set {
                this["CheckedInTimeHours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public long CheckedInSpecimenRefresh {
            get {
                return ((long)(this["CheckedInSpecimenRefresh"]));
            }
            set {
                this["CheckedInSpecimenRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ARUPSRC\\chris-crofts-master@3e0293afad3\\Thaw Mix Dashboard\\bin\\Debug")]
        public string ScannerLocation {
            get {
                return ((string)(this["ScannerLocation"]));
            }
            set {
                this["ScannerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int ThawMixAppId {
            get {
                return ((int)(this["ThawMixAppId"]));
            }
            set {
                this["ThawMixAppId"] = value;
            }
        }
    }
}
